[package]
name = "ex-caller"
version = "0.4.2"
description = "一个简约风格的随机点名工具"

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = [] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
tauri-plugin-dialog = "2.0.0-beta"
tauri-plugin-fs = "2.0.0-beta"
tauri-plugin-shell = "2.0.0-beta"

[features]
custom-protocol = [ "tauri/custom-protocol" ]
